<?php

namespace chaseburklund\entryporter\port;

/**
 * Routes each field to the first registered transformer that supports its class, or to the
 * fallback transformer when none does.
 */
final class Registry
{
    /**
     * The payload format version this install writes.
     *
     * Raise it whenever older installs would misread a new payload rather than simply ignore
     * what they do not understand, and keep older versions that are still readable in
     * SUPPORTED_PAYLOAD_VERSIONS. Version 2 renamed the rich-text marker from `ckeditor` to
     * `htmlfield`, which version 1 installs would have imported as a corrupt value.
     */
    public const PAYLOAD_VERSION = 2;

    /**
     * The payload format versions this install can import.
     *
     * @var int[]
     */
    public const SUPPORTED_PAYLOAD_VERSIONS = [1, 2];

    /** Returned by a transformer to leave a field out of the payload or the import. */
    public const SKIP = ['__portable' => 'skip'];

    /**
     * Reasons a field was skipped. The reason travels in the payload so the import report can
     * explain it: an unportable field has to be set by hand on the target, while a derived
     * field (such as SEOmatic's optimized images) is regenerated by the target and needs no
     * action. Only these tokens are recognized, so a payload cannot put arbitrary text into
     * the report.
     */
    public const SKIP_UNPORTABLE = 'unportable';
    public const SKIP_DERIVED = 'derived';

    /** @var string[] the only reasons skipReason() will report */
    public const SKIP_REASONS = [self::SKIP_UNPORTABLE, self::SKIP_DERIVED];

    /** SKIP with a reason attached. */
    public static function skip(string $reason): array
    {
        return self::SKIP + ['reason' => $reason];
    }

    /** The reason a SKIP carries, or null when it carries no recognized reason. */
    public static function skipReason(mixed $v): ?string
    {
        if (!self::isSkip($v)) {
            return null;
        }
        $reason = $v['reason'] ?? null;
        return is_string($reason) && in_array($reason, self::SKIP_REASONS, true) ? $reason : null;
    }

    /** @var TransformerInterface[] */
    private array $transformers = [];

    public function __construct(private readonly TransformerInterface $fallback)
    {
    }

    public static function isSkip(mixed $v): bool
    {
        return is_array($v) && ($v['__portable'] ?? null) === 'skip';
    }

    public function add(TransformerInterface $t): void
    {
        $this->transformers[] = $t;
    }

    public function export(FieldDescriptor $field, mixed $value, ResolverInterface $resolver, Report $report): mixed
    {
        return $this->for($field->class)->export($field, $value, $resolver, $report);
    }

    public function import(FieldDescriptor $field, mixed $value, ResolverInterface $resolver, Report $report): mixed
    {
        return $this->for($field->class)->import($field, $value, $resolver, $report);
    }

    private function for(string $fieldClass): TransformerInterface
    {
        foreach ($this->transformers as $t) {
            if ($t->supports($fieldClass)) {
                return $t;
            }
        }
        return $this->fallback;
    }
}
